name: CI/CD Frontend Only

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GIT_PRIVATE_KEY }}

      - name: Deploy Frontend ke EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'

            echo "=== UPDATE FRONTEND ==="
            cd /var/www/nama-project
            git pull origin main

            echo "=== RESTART NGINX ==="
            sudo systemctl restart nginx

          EOF